# Generated by Django 5.2.3 on 2025-09-26 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('job', 'Job Opportunity'), ('collaboration', 'Collaboration'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=50)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Benedict Nii Odartey Mensah', max_length=100)),
                ('preferred_name', models.CharField(default='Benny', max_length=50)),
                ('title', models.CharField(default='Full-Stack Developer', max_length=100)),
                ('hero_description', models.TextField(help_text='Main description for hero section')),
                ('about_description', models.TextField(help_text='Detailed about section')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, upload_to='documents/')),
                ('portfolio_url', models.URLField(blank=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('framework', 'Framework'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=50)),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=2)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on main page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', unique=True)),
                ('short_description', models.TextField(help_text='Brief description for project cards', max_length=300)),
                ('detailed_description', models.TextField(blank=True, help_text='Detailed project description')),
                ('live_url', models.URLField(blank=True, help_text='Live project URL', validators=[django.core.validators.URLValidator()])),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', validators=[django.core.validators.URLValidator()])),
                ('featured_image', models.ImageField(blank=True, help_text='Main project screenshot', upload_to='projects/')),
                ('demo_video', models.FileField(blank=True, help_text='Optional demo video', upload_to='projects/videos/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as featured project')),
                ('is_published', models.BooleanField(default=True, help_text='Show on website')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying projects (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, help_text='Technologies used in this project', to='main.skill')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('tutorial', 'Tutorial'), ('personal', 'Personal'), ('project', 'Project Update')], default='tech', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='main.skill')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
